### ISSUE TITLE
Require JS AMD Support

### ISSUE THREAD

**Issue by jonathanamartin** [ramiel/router.js#12]
Hey Ramiel,

Does this router support AMD?  We'd like to use it as an AMD/Require JS module in our app.

**Comment by ramiel** [comment]
Yes of course! As pointed in documentation you can use require.js (AMD) to include this library.
Let me know if it works for your application.

**Comment by jonathanamartin** [comment]
Wow... I can't believe I missed that.  My apologies.  Thanks for the quick feedback.

**Comment by ramiel** [comment]
Nothing!
