### ISSUE TITLE
Named AMD definition

### ISSUE THREAD

**Issue by indaduke** [ramiel/router.js#13]
Hi Ramiel,

I noticed in your AMD definition you are using an anonymous definition.  I'm guessing this is so that in the requires configuration it could be given any name.  The issue I'm running into is that we are trying to concatenate multiple third party JS libraries and with the anonymous definition I have no way to require just this one module.  The way I could make it work is if I changed your line of 

else if ((typeof define == 'function' && typeof define.amd == 'object') define(definition);}

to 

else if ((typeof define == 'function') && (typeof define.amd == 'object')){define('router', [], definition);}

Doing this does make user have to use 'router' in their requiejs configuration but also allows this library to be concatenated to other libraries.

If you have other ideas how we can get around this issue I would be happy to hear them.  This was the one way I could see how it could be done and looks like the way some other libraries handle allowing their libraries to be bundled.

Thanks,
Josh

**Comment by ramiel** [comment]
Hi indaduke,
as stated <http://requirejs.org/docs/api.html#modulename> :

> You may encounter some define() calls that include a name for the module as the first argument to
> define():
> ```javascript
>   //Explicitly defines the "foo/title" module:
>   define("foo/title",
>      ["my/cart", "my/inventory"],
>        function(cart, inventory) {
>            //Define foo/title object in here.
>       }
>    );
>```
>These are normally generated by the optimization tool. You can explicitly name modules yourself, but it makes the modules less portable -- if you move the file to another directory you will need to change the name. It is normally best to avoid coding in a name for the module and just let the optimization tool burn in the module names. The optimization tool needs to add the names so that more than one module can be bundled in a file, to allow for faster loading in the browser.

There should be no difference between  having a named and not named module. Are you sure you're requiring it the correct way? Can you post your code and your folders structure?

**Comment by ramiel** [comment]
Any news on this?
