### ISSUE TITLE
Can the routing module have some hooks to get the last route of the current routing?

### ISSUE THREAD

**Issue by caihuattkl** [ramiel/router.js#23]
Can the routing module have some hooks to get the last route of the current routing?

**Comment by caihuattkl** [comment]
I want to get the last route that can't be realized?

**Comment by ramiel** [comment]
Do you mean you want to execute a function when no route matches the current URL?

**Comment by caihuattkl** [comment]
Yes, it's one of the needs。

**Comment by ramiel** [comment]
So you can use the error handler for the 404 case

```js
router
  .errors(404, function( err, href){
    alert('Page not found!' + href );
  });
```

this will match any unmatching route and you have access to href in the handler

**Comment by caihuattkl** [comment]
Thank you. It's beginning to understand.

**Comment by ramiel** [comment]
Great!
