### ISSUE TITLE
Why not return an attribute to record the current routing address?

### ISSUE THREAD

**Issue by caihuattkl** [ramiel/router.js#25]
Why not return an attribute to record the current routing address?Sometimes, we need to get this routing address

**Comment by ramiel** [comment]
In every route you can get the routing address through `req.href`.

**Comment by caihuattkl** [comment]
This routing module has the previous route of the current routing, that is, the current routing source.

**Comment by ramiel** [comment]
SOrry @caihuattkl I can't understand your request. Can you explain it better?
