### ISSUE TITLE
This routing module has the previous route of the current routing, that is, the current routing source.

### ISSUE THREAD

**Issue by caihuattkl** [ramiel/router.js#26]
This routing module has the previous route of the current routing, that is, the current routing source.

**Comment by caihuattkl** [comment]
If you add this function, it's perfect.

**Comment by ramiel** [comment]
Sorry @caihuattkl I can't understand your request. Can you explain it better?

**Comment by caihuattkl** [comment]
My English is not good. Forgive me

**Comment by caihuattkl** [comment]
OK. This is a very common function!

**Comment by caihuattkl** [comment]
vue-router It's a good routing module that doesn't support jquery
