### ISSUE TITLE
Img inside anchor

### ISSUE THREAD

**Issue by OR-75** [ramiel/router.js#43]
Hy,
May be i did something wrong, but it seems that the router doesn't catch the route when inside the anchor there is just an img :
```
<a href="/foo">
  <img src="image.jpg" alt="image" />
</a>
```

**Comment by ramiel** [comment]
It is possible. I will check soon.

**Comment by ramiel** [comment]
Ok, I just solved the issue and the fix is available in latest version, 2.4.1. Bye!
